CREATE TABLE trading_pair
(
    id              BIGINT         NOT NULL AUTO_INCREMENT,
    symbol          VARCHAR(20)    NOT NULL,
    gateway         VARCHAR(50)    NOT NULL,
    wallet          DECIMAL(19, 8) NOT NULL,
    active          BOOLEAN        NOT NULL DEFAULT TRUE,
    order_count     INT            NOT NULL DEFAULT 0,
    spend_per_order DECIMAL(19, 8) NULL,
    profit_percent  DECIMAL(5, 2) NULL,
    CONSTRAINT pk_trading_pair PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trading_pair_id BIGINT         NOT NULL REFERENCES trading_pair (id),
    market_order_id VARCHAR(100),
    type            VARCHAR(10)    NOT NULL,
    price           DECIMAL(20, 8) NOT NULL,
    qty             DECIMAL(20, 8) NOT NULL,
    status          VARCHAR(30)    NOT NULL,
    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP      NOT NULL
);